version: '3'

services:
  ssserver-rust:
    image: petermatthew/ssserver-rust
    container_name: ssserver-rust
    restart: always
    # ports: # 映射端口，如果需要让其他机器访问，请取消注释
    #   - '8388:8388/udp'
    #   - '8388:8388/tcp'
    volumes:
      - ./server.ssconfig.json:/.ssconfig.json:ro
    environment:
      - DNS_ADDRS=114.114.114.114,8.8.8.8
  # sslocal-rust:
  #   image: petermatthew/sslocal-rust
  #   container_name: sslocal-rust
  #   restart: always
  #   ports:
  #     - '1080:1080/udp'
  #     - '1080:1080/tcp'
  #   volumes:
  #     - ./local.ssconfig.json:/.ssconfig.json:ro
  # ssserver-manager-rust:
  #   image: petermatthew/ssserver-manager:latest-alpine
  #   container_name: ssserver-manager-rust
  #   restart: always
  #   volumes:
  #     - ./manager.server.ssconfig.json:/.ssconfig.json:ro
  #   ports:
  #     # - "8388:8388/udp"   # ss-server 代理端口
  #     # - "8388:8388/tcp"   # ss-server 代理端口
  #     - "6000:6000"   # 管理界面端口
  sslocal-manager-rust:
    image: petermatthew/sslocal-manager:latest-alpine
    container_name: sslocal-manager-rust
    restart: always
    volumes:
      - ./manager.local.ssconfig.json:/.ssconfig.json:ro
    ports:
      - "1080:1080/udp"   # ss-local 代理端口
      - "1080:1080/tcp"   # ss-local 代理端口
      - "5000:5000"   # 管理界面端口
    
# networks: # 网络配置，需要使用 IPv6 时取消注释
#   default:
#     enable_ipv6: true
