version: '3'

services:
  ssserver-rust:
    image: petermatthew/ssserver-rust
    container_name: ssserver-rust
    restart: always
    ports:
      - '8388:8388/udp'
      - '8388:8388/tcp'
    volumes:
      - ./.ssconfig.json:/.ssconfig.json:ro
