version: '3'

services:
  ss-manager:
    image: petermatthew/ssserver-manager:latest-alpine
    container_name: ss-manager
    restart: always
    volumes:
      - ./.ssconfig.json:/.ssconfig.json:ro
    ports:
      - "8388:8388/udp"   # ss-server 代理端口
      - "8388:8388/tcp"   # ss-server 代理端口
      - "6000:6000"   # 管理界面端口
    
# networks: # 网络配置，需要使用 IPv6 时取消注释
#   default:
#     enable_ipv6: true
