name: Build Docker Image

on:
  push:
    branches:
      - ssserver-rust

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ssserver-rust
      
      - uses: docker/setup-buildx-action@v3

      - name: Extract current date
        id: extract-date
        run: |
          DATE=$(date +%Y%m%d)
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ssserver-rust-test:latest
            ssserver-rust-test:${{ steps.extract-date.outputs.date }}
